DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
--회원등급 
DROP TABLE MEMBER_GRADE CASCADE CONSTRAINTS;
DROP TABLE MEMBER_GRADE;
SELECT * FROM MEMBER_GRADE;
CREATE TABLE MEMBER_GRADE(
    mGRADE NUMBER(1,0) PRIMARY KEY,
    GRADENAME VARCHAR2(20), 
    LOW NUMBER(13),
    HIGH NUMBER(13));
    
--MEMBER_GRADE DUMMY
INSERT INTO MEMBER_GRADE VALUES(5,'NORMAL', 0, 99);
INSERT INTO MEMBER_GRADE VALUES(4,'SILVER', 100, 499);
INSERT INTO MEMBER_GRADE VALUES(3,'GOLD', 500, 999);
INSERT INTO MEMBER_GRADE VALUES(2,'VIP', 1000, 1999);
INSERT INTO MEMBER_GRADE VALUES(1,'VVIP', 2000, 9999999999999);
SELECT * FROM MEMBER_GRADE ORDER BY MGRADE ;    

--회원
DROP TABLE MEMBER;
SELECT * FROM MEMBER;
CREATE TABLE MEMBER (
    mID  VARCHAR2(50) PRIMARY KEY,
    mGRADE NUMBER(1,0) DEFAULT 5,
    mNAME VARCHAR2(50) NOT NULL,
    mPW VARCHAR2(50) NOT NULL,
    mTEL VARCHAR2(50) NOT NULL,
    mEMAIL VARCHAR2(50),
    mADDRESS VARCHAR2(250),
    mGENDER VARCHAR2(10) NOT NULL,
    mBirth date,
    FOREIGN KEY(mGRADE) REFERENCES MEMBER_GRADE(mGRADE)
    );

--MEMBER DUMMY
INSERT INTO MEMBER(MID,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER,mbirth)
    VALUES('ZICO','지코','1','010-1111-1111','ZICO@NAVER.COM','서울시 강남구','남','1992-05-13');
INSERT INTO MEMBER(MID,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER)
    VALUES('KANG','강동원','1','010-2222-2222','KANG@NAVER.COM','서울시 용산구','남');  
INSERT INTO MEMBER(MID,MGRADE,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER)
    VALUES('jo',5,'조강옥','1','010-3333-3333','JO@NAVER.COM','서울시 용산구','남');
SELECT * FROM MEMBER;    
    
--자유게시판
SELECT * FROM BOARD;
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;    
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE BOARD(
    bNO NUMBER(7) PRIMARY KEY ,
    mID VARCHAR2(50) REFERENCES MEMBER(mID) ,
    bSUBJECT VARCHAR2(100) NOT NULL,
    bCONTENT VARCHAR2(3000) NOT NULL,
    bFILE VARCHAR2(100) ,
    bHIT NUMBER(6) DEFAULT 0,
    bGROUP NUMBER(6) NOT NULL,
    bSTEP  NUMBER(6)  NOT NULL,
    bINDENT  NUMBER(6) NOT NULL,
    bIP VARCHAR2(30) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE,
    mGRADE NUMBER(1,0) DEFAULT 5,
    FOREIGN KEY(mGRADE) REFERENCES MEMBER_GRADE(mGRADE)
   );
select * from board;    

--관리자 
CREATE TABLE ADMIN(
    aID VARCHAR2(50) PRIMARY KEY,
    apW VARCHAR2(50) NOT NULL
);
select * from admin;
--CAR_DESIGN
DROP TABLE CAR_DESIGN CASCADE CONSTRAINTS;
CREATE TABLE CAR_DESIGN(
    designID VARCHAR2(50) PRIMARY KEY,
    designNAME VARCHAR2(50)
);
--DESIGN DUMMY
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(10,'SEDAN');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(20,'SUV');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(30,'COUPE');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(40,'Carbirolet');
SELECT * FROM CAR_DESIGN;
--CAR_BRAND
DROP TABLE CAR_BRAND CASCADE CONSTRAINTS;
CREATE TABLE CAR_BRAND(
    brandID  VARCHAR2(30) PRIMARY KEY,
    brandNAME VARCHAR2(100) 
    );
-- BRAND DUMMY    
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B1','BMW');   
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B2','BENZ');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B3','AUDI');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B4','MASERATI');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B5','PORSCHE');

SELECT * FROM CAR_BRAND;
--CAR   

DROP SEQUENCE CAR_SEQ;    
CREATE SEQUENCE CAR_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT * FROM CAR;
CREATE TABLE CAR(
    CID VARCHAR2(10) PRIMARY KEY ,
    brandID VARCHAR2(50) REFERENCES CAR_BRAND(brandID),
    CARNAME VARCHAR2(50) UNIQUE,
    designID VARCHAR2(50) REFERENCES CAR_DESIGN(designID),
    cPRICE NUMBER(12) NOT NULL,
    cFUEL VARCHAR2(50) NOT NULL,
    cMILE VARCHAR2(50),
    cPHOTO VARCHAR2(150),
    FOREIGN KEY(brandID) REFERENCES CAR_BRAND(brandID),
    FOREIGN KEY(designID) REFERENCES CAR_DESIGN(designID)
);   

--ESTIMATE 자동차 견적 
DROP TABLE ESTIMATE;
DROP SEQUENCE ESTIMATE_SEQ;

CREATE SEQUENCE ESTIMATE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE ESTIMATE (    
    EID NUMBER(2) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID),
    BRANDNAME VARCHAR2(10),
    carname VARCHAR2(50) REFERENCES CAR(CARNAME),
    PREPAYMENT NUMBER(3) ,
    TERM NUMBER(2),   
    CPLACE VARCHAR2(200) REFERENCES CAR_DISPLAY,
    PAY NUMBER(10)
    );
SELECT * FROM estimate where eid ='1';

--CAR_DISPLAY 전시장
CREATE TABLE CAR_DISPLAY (CPLACE VARCHAR2(200) PRIMARY KEY);
select * from car_display;

--car_reserve 시승예약
drop SEQUENCE car_reserve_SEQ;
CREATE SEQUENCE car_reserve_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
DROP TABLE CAR_RESERVE;
create table car_reserve (
   rID NUMBER(3) PRIMARY KEY,
   mname VARCHAR2(50) not null ,  
   mtel varchar2(50) not null,
   brandname varchar2(100) not null,
   CarNAME VARCHAR2(50) NOT NULL,
   CRDATE DATE NOT NULL, 
   cPLACE VARCHAR2(200) not null
);
rollback;
select to_char(crdate, 'hh:mm') from car_reserve;
insert into car_reserve (RID,mname, mtel,brandname,carname,crdate,cplace)
    values(car_reserve_SEQ.NEXTVAL,'조강옥','010-4123-4312','AUDI','A4', '2022-07-06','서울시 강남구 청담동');
select * from car_reserve;   

select * from car_reserve where mname='조강옥';

SELECT distinct brandNAME FROM CAR C, CAR_BRAND B;

SELECT DISTINCT BRANDNAME , CARNAME FROM CAR C, CAR_BRAND B 
WHERE C.BRANDID = B.BRANDID ORDER BY BRANDNAME;
commit; 

--댓글 한줄평 
create sequence comment_seq MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE BOARD_COMMENT(
    CNO       NUMBER(6) PRIMARY KEY,
    CMEMO       VARCHAR2(1000) NOT NULL,
    MID         VARCHAR2(50) REFERENCES MEMBER(MID),
    BNO         NUMBER(7) REFERENCES BOARD(BNO),
    CDATE     DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE BOARD ADD BOARD_COUNT NUMBER(20) DEFAULT 0;    
SELECT * FROM BOARD_comment;    

--메세지 
drop table msg;
create sequence msg_seq MAXVALUE 99999 NOCACHE NOCYCLE;
create table msg (
    msid  NUMBER(6) PRIMARY KEY,
    mname varchar2(30) not null, 
    memail  varchar2(100) not null ,
    mphone number(11) not null,
    memo varchar2(200)
);