DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
--회원등급 
DROP TABLE MEMBER_GRADE CASCADE CONSTRAINTS;
DROP TABLE MEMBER_GRADE;
SELECT * FROM MEMBER_GRADE;
CREATE TABLE MEMBER_GRADE(
    mGRADE NUMBER(1,0) PRIMARY KEY,
    GRADENAME VARCHAR2(20), 
    LOW NUMBER(13),
    HIGH NUMBER(13));
    
--MEMBER_GRADE DUMMY
INSERT INTO MEMBER_GRADE VALUES(5,'NORMAL', 0, 99);
INSERT INTO MEMBER_GRADE VALUES(4,'SILVER', 100, 499);
INSERT INTO MEMBER_GRADE VALUES(3,'GOLD', 500, 999);
INSERT INTO MEMBER_GRADE VALUES(2,'VIP', 1000, 1999);
INSERT INTO MEMBER_GRADE VALUES(1,'VVIP', 2000, 9999999999999);
SELECT * FROM MEMBER_GRADE ORDER BY MGRADE ;    

--회원
DROP TABLE MEMBER;
SELECT * FROM MEMBER;
CREATE TABLE MEMBER (
    mID  VARCHAR2(50) PRIMARY KEY,
    mGRADE NUMBER(1,0) DEFAULT 5,
    mNAME VARCHAR2(50) NOT NULL,
    mPW VARCHAR2(50) NOT NULL,
    mTEL VARCHAR2(50) NOT NULL,
    mEMAIL VARCHAR2(50),
    mADDRESS VARCHAR2(250),
    mGENDER VARCHAR2(10) NOT NULL,
    mBirth date,
    FOREIGN KEY(mGRADE) REFERENCES MEMBER_GRADE(mGRADE)
    );

--MEMBER DUMMY
INSERT INTO MEMBER(MID,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER,mbirth)
    VALUES('ZICO','지코','1','010-1111-1111','ZICO@NAVER.COM','서울시 강남구','남','1992-05-13');
INSERT INTO MEMBER(MID,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER)
    VALUES('KANG','강동원','1','010-2222-2222','KANG@NAVER.COM','서울시 용산구','남');  
INSERT INTO MEMBER(MID,MGRADE,MNAME,MPW,MTEL,MEMAIL,MADDRESS,MGENDER)
    VALUES('jo',5,'조강옥','1','010-3333-3333','JO@NAVER.COM','서울시 용산구','남');
SELECT * FROM MEMBER;    
    
--자유게시판
SELECT * FROM BOARD;
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;    
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE BOARD(
    bNO NUMBER(7) PRIMARY KEY ,
    mID VARCHAR2(50) REFERENCES MEMBER(mID) ,
    bSUBJECT VARCHAR2(100) NOT NULL,
    bCONTENT VARCHAR2(3000) NOT NULL,
    bFILE VARCHAR2(100) ,
    bHIT NUMBER(6) DEFAULT 0,
    bGROUP NUMBER(6) NOT NULL,
    bSTEP  NUMBER(6)  NOT NULL,
    bINDENT  NUMBER(6) NOT NULL,
    bIP VARCHAR2(30) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE,
    mGRADE NUMBER(1,0) DEFAULT 5,
    FOREIGN KEY(mGRADE) REFERENCES MEMBER_GRADE(mGRADE)
   );
    
--관리자 
CREATE TABLE ADMIN(
    aID VARCHAR2(50) PRIMARY KEY,
    apW VARCHAR2(50) NOT NULL
);
select * from admin;
--CAR_DESIGN
DROP TABLE CAR_DESIGN CASCADE CONSTRAINTS;
CREATE TABLE CAR_DESIGN(
    designID VARCHAR2(50) PRIMARY KEY,
    designNAME VARCHAR2(50)
);
--DESIGN DUMMY
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(10,'SEDAN');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(20,'SUV');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(30,'COUPE');
INSERT INTO CAR_DESIGN(designID,desiGNNAME)VALUES(40,'Carbirolet');
SELECT * FROM CAR_DESIGN;
--CAR_BRNAD
DROP TABLE CAR_BRAND CASCADE CONSTRAINTS;
CREATE TABLE CAR_BRAND(
    brandID  VARCHAR2(30) PRIMARY KEY,
    brandNAME VARCHAR2(100) 
    );
-- BRAND DUMMY    
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B1','BMW');   
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B2','BENZ');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B3','AUDI');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B4','MASERATI');
INSERT INTO CAR_BRAND(brandID,brandNAME) VALUES('B5','PORSCHE');

SELECT * FROM CAR_BRAND;
--CAR   

DROP SEQUENCE CAR_SEQ;    
CREATE SEQUENCE CAR_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT * FROM CAR;
CREATE TABLE CAR(
    CID VARCHAR2(10) PRIMARY KEY ,
    brandID VARCHAR2(50) REFERENCES CAR_BRAND(brandID),
    CARNAME VARCHAR2(50) UNIQUE,
    designID VARCHAR2(50) REFERENCES CAR_DESIGN(designID),
    cPRICE NUMBER(12) NOT NULL,
    cFUEL VARCHAR2(50) NOT NULL,
    cMILE VARCHAR2(50),
    cPHOTO VARCHAR2(150),
    FOREIGN KEY(brandID) REFERENCES CAR_BRAND(brandID),
    FOREIGN KEY(designID) REFERENCES CAR_DESIGN(designID)
);   
--ESTIMATE 자동차 견적 
DROP TABLE ESTIMATE;
CREATE TABLE ESTIMATE (cID VARCHAR2(10) REFERENCES CAR(cid));
SELECT * FROM CAR;

--CAR_DISPLAY 전시장
CREATE TABLE CAR_DISPLAY (CPLACE VARCHAR2(200) PRIMARY KEY);
select * from car_display;
--car_reserve 시승
create table car_reserve (
   mid VARCHAR2(50) REFERENCES MEMBER(mID) ,
   cid varchar2(10) REFERENCES CAR(CID),
   CRDATE DATE NOT NULL,
   cPLACE VARCHAR2(200),
   mGRADE NUMBER(1,0)  REFERENCES MEMBER_GRADE(mGRADE)   
);


 
    
    
